name: Hadolint

on: [push]

jobs:
  lint-docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint (v3)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          args: --ignore DL3008
